### ISSUE TITLE
Problem with DROD RPG MIDs

### ISSUE THREAD

**Issue by Hypexion** [CaravelGames/drod#308]
It appears that #299 added a new MID in the middle of the existing ones, instead of adding it to the end. This has shifted a bunch of MIDs by one, which completely mangles the DROD RPG interface if you try using an existing .dat file to play. Making this an issue because I'm not sure of the best way to get this fixed.

**Comment by mrimer** [comment]
Ah, sorry about that.  This can be addressed by reverting to the original numbering and taking the new MIDs and placing them at the end of the numbering.

Please feel free to submit a PR with this correction if you like.

**Comment by mrimer** [comment]
Thank you for PR #314 to resolve this.  Closing this issue.
