### ISSUE TITLE
UI Naming conventions

### ISSUE THREAD

**Issue by EvidentlyCube** [CaravelGames/drod#311]
In my Puzzle Mode Options dialog PR I've changed slightly the existing naming conventions for the UI elements, aiming to make it slightly more legible. My specific issues were:

- Putting X/Y/CX/CY at the start of variable name is for me detrimental to readability, because usually you're less interested about the specific dimensions (since almost always you already have the context of what you're looking for) and more about the component for that dimension.
- It also makes it more difficult to group variables for the same element easily visually.
- CX/CY looks eerily similar to X/Y, I am always confused and need to pay triple attention to know what I am looking at

I am asking for permission to change the convention whenever I am doing any significant work or new, isolated work on any of the existing components - specifically it would be for Settings Screen at the moment, since I am working on adding the new keymapping options.

@mrimer

**Comment by mrimer** [comment]
Ah, yes. If I'm understanding, you're talking about swapping the prepended `{X,Y,CX,CY}_` with an appended `_{X,Y,W,H}`.  Your proposed style seems easier for me to read too.  Sure, I'm fine with using/updating to the new convention whenever it makes sense in development.  I'll start using the new convention too.

**Comment by EvidentlyCube** [comment]
Yup, exactly that. Glad to have your green light for that! Closing.
