### ISSUE TITLE
UNI file encoding

### ISSUE THREAD

**Issue by Hypexion** [CaravelGames/drod#80]
Currently, the .uni files that contain all the game strings use UCS-2 encoding. It appears that very few tools recognise these files as being text files, including the Github web interface. This makes them difficult to work with, especially if a merge conflict occurs.

Once DROD 5.2 and RPG 1.3 are done, we might want to look into changing the encoding to one that's more widely supported.

**Comment by EvidentlyCube** [comment]
I'd suggest UTF-8 which is de-facto standard everywhere nowadays. No clue how much of a pain it would be to use it in C++ though.

**Comment by mrimer** [comment]
I agree this is a pain.  I believe this format is tightly coupled with the CDbMessageText database format that, IIRC, expects UCS-2.
I could be wrong about this, but that would likely be the place to look first to make a format change.

**Comment by EvidentlyCube** [comment]
I think it's fine to keep the format internally, nothing stops us from converting from whatever format we use to UCS-2.

**Comment by Hypexion** [comment]
Having done some very brief research on this, it seems like if the format is changed, we'd want to change to UTF-16. It seems to be the case that UCS-2 is an older implementation of the Unicode specification, that is obselete now that UTF-16 exists.

Poking around in the DROD source, all the string functions are using `WSTRING` and `WCHAR`. `Wchar.h` in BackEndLib claims that these are 16 bit unicode characters, so it should probably be fine to switch over to UTF-16 encoding.

The next step forward is probably to just do it, and see if the strings still get imported correctly by DRODUtil.

**Comment by mrimer** [comment]
Sure!  What you say makes sense to me.  I don't want to stand in the way of progress.  Please go ahead and try it out if you like and if it works, then great!

**Comment by mrimer** [comment]
> I think it's fine to keep the format internally, nothing stops us from converting from whatever format we use to UCS-2.

That's a great point too.  I often forget about interface boundaries.  We do have a bunch of conversion routines already, and we can do more of the same in WChar/DRODUtil if we wish without changing the internal DB format.

**Comment by Hypexion** [comment]
Belated update: Having looked into this some more, the big issue is that git essentially doesn't support UTF-16 or UCS-2. Switching between them won't help. If we want the uni files to play nicely with Git, we'd probably want to convert them to UTF-8, then change DRODUtil to deal with that change.

**Comment by mrimer** [comment]
Merged PR #428 into 5.2.  If we want, we may also do this for RPG.

**Comment by Hypexion** [comment]
> Merged PR #428 into 5.2. If we want, we may also do this for RPG.

I'll get it done. I didn't do the two in parallel just in case there was an unexpected problem with the changes.

**Comment by mrimer** [comment]
Sir, you are a gentleman and a scholar! Thank you.

**Comment by mrimer** [comment]
@Hypexion , am I correct in understanding we may now close this issue?

**Comment by Hypexion** [comment]
> @Hypexion , am I correct in understanding we may now close this issue?

I think so. If any other encoding issues show up, we can always open a new one.
